---
language: python
python:
  - 3.8

services:
  - docker

env:
  global:
    - ROLE_NAME: gdnsd
  matrix:
    - MOLECULE_DISTRO: debian10

install:
  - pip install ansible ansible-lint molecule[docker]
  - molecule --version
  - ansible --version
  - ansible-lint --version

before_script:
  - cd ../
  - mv -v ansible-$ROLE_NAME ganto.$ROLE_NAME
  - cd ganto.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
