---
language: python
python:
  - 3.8

sudo: false

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible
  - pip install ansible yamllint ansible-lint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path = .\ninventory = tests/inventory\nretry_files_enabled = false\n' > ansible.cfg

  # Symlink role name to repository
  - ln -s . gdnsd

script:
  # Basic role syntax check
  - ansible-playbook --syntax-check tests/test.yml

  # YAML syntax linter
  - yamllint .

  # Ansible linter
  - ansible-lint -v --exclude='./gdnsd'
