---
- name: Converge
  hosts: all

  vars:
    gdnsd__custom_packages:
      - netbase
    gdnsd__zones:
      # domain without records
      - domain: example.net
        auto_reverse_zone: False
      - domain: example.com
        records:
          - name: '{{ ansible_hostname }}'
            target: '{{ ansible_default_ipv4.address }}'
          - name: '@'
            type: AAAA
            target: '2606:2800:220:1:248:1893:25c8:1946'
            do_reverse: false
          - name: '@'
            target: '{{ ansible_default_ipv4.address }}'
            do_reverse: false
          - name: www
            type: CNAME
            target: example.com
          - name: ansible
            type: TXT
            target: "tested-by=molecule"
          - type: MX
            target: '{{ ansible_default_ipv4.address }}'

  roles:
    - role: ganto.gdnsd
