---
- name: Converge
  hosts: all

  vars:
    gdnsd__custom_packages:
      - netbase
    gdnsd__zones:
      - domain: example.com
        records:
          - name: '{{ ansible_hostname }}'
            target: '{{ ansible_default_ipv4.address }}'
          - name: '@'
            type: AAAA
            target: '2606:2800:220:1:248:1893:25c8:1946'
            do_reverse: false
          - name: '@'
            target: '{{ ansible_default_ipv4.address }}'
            do_reverse: false
          - name: www
            type: CNAME
            target: example.com
          - name: ansible
            type: TXT
            target: "tested-by=molecule"
          - type: MX
            target: '{{ ansible_default_ipv4.address }}'

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: ganto.gdnsd
