---
dependency:
  name: galaxy
  enabled: False
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint --exclude molecule/ .
platforms:
  - name: instance
    image: debian:buster
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
